[package]
name = "gkr"
version = "0.1.0"
edition = "2021"

[dependencies]
polynomials = { path = "../polynomials" }
sumcheck_protocol = { path = "../sumcheck_protocol" }
circuit = { path = "../circuit" }
transcripts = { path = "../transcripts"}
ark-ff = "0.5.0"
ark-bn254 = "0.5.0"