[package]
name = "gkr"
version = "0.1.0"
edition = "2021"

[dependencies]
polynomials = { path = "../polynomials" }
sumcheck_protocol = { path = "../sumcheck_protocol" }
circuit = { path = "../circuit" }