[package]
name = "multilinear_kzg"
version = "0.1.0"
edition = "2021"

[dependencies]
polynomials = { path = "../polynomials" }
ark-ff = "0.5.0"
ark-ec = "0.5.0"
rand = "0.8.5"
ark-bls12-381 = "0.5.0"